Algoritmo SUMA
	DEFINIR NUM1 Como Entero
	DEFINIR NUM2 COMO ENTERO
	DEFINIR RESULTADO Como Entero
	
	Escribir "INGRESA PRIMER NUMERO"
	LEER NUM1
	Escribir "INGRESA SEGUNDO NUMERO"
	LEER NUM2
	
	RESULTADO = NUM1 + NUM2
	
	Escribir "EL RESULTADO ES",RESULTADO
FinAlgoritmo
